/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-31 18:32:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.techhub.service.*;
import org.techhub.model.*;

public final class UpdateAlumni_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("org.techhub.service");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.techhub.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Update Alumni</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/update.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"JS/update.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"nav flex-column nav-pills menubar bg-light\" id=\"v-pills-tab\" role=\"tablist\" aria-orientation=\"vertical\">\r\n");
      out.write("                    <a class=\"nav-link active\" id=\"v-pills-home-tab\" data-toggle=\"pill\" href=\"index.jsp\" role=\"tab\" aria-controls=\"v-pills-home\" aria-selected=\"true\">Batch Master</a>\r\n");
      out.write("                    <a class=\"nav-link\" id=\"v-pills-profile-tab\" data-toggle=\"pill\" href=\"Alumnimaster.jsp\" role=\"tab\" aria-controls=\"v-pills-profile\" aria-selected=\"false\">Alumni Master</a>\r\n");
      out.write("                    <a class=\"nav-link\" id=\"v-pills-messages-tab\" data-toggle=\"pill\" href=\"#v-pills-messages\" role=\"tab\" aria-controls=\"v-pills-messages\" aria-selected=\"false\">Event Master</a>\r\n");
      out.write("                    <a class=\"nav-link\" id=\"v-pills-settings-tab\" data-toggle=\"pill\" href=\"#v-pills-settings\" role=\"tab\" aria-controls=\"v-pills-settings\" aria-selected=\"false\">Feedback Master</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-9 content\">\r\n");
      out.write("                <div class=\"tab-content\" id=\"v-pills-tabContent\">\r\n");
      out.write("                    <div class=\"tab-pane fade show active\" id=\"v-pills-home\" role=\"tabpanel\" aria-labelledby=\"v-pills-home-tab\">\r\n");
      out.write("                        <div class=\"form-container mt-12\">\r\n");
      out.write("                        <h3>Update Alumni</h3>\r\n");
      out.write("                            <label>Do you want to update the Alumni details?</label>\r\n");
      out.write("                            <select class=\"form-control bg-light text-dark mt-2\" id=\"updateOption\" onchange=\"toggleFields(this.value)\">\r\n");
      out.write("                                <option value=\"\">Select</option>\r\n");
      out.write("                                <option value=\"yes\">Yes</option>\r\n");
      out.write("                                <option value=\"no\">No</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <form name='frm' id=\"frm\" action='update' method='GET'>\r\n");
      out.write("                                <div id=\"updateFields\" style=\"display: none;\">\r\n");
      out.write("                                    <div class=\"form-group mt-3\">\r\n");
      out.write("                                        <label for=\"aidSelect\">Select Alumni ID</label>\r\n");
      out.write("                                        <select class=\"form-control\" id=\"aidSelect\" name=\"aid\">\r\n");
      out.write("                                            <option value=\"\">Select ID</option>\r\n");
      out.write("                                            ");

                                            Alumnimasterservice amservice = new AlumniMasterServiceImpl();
                                            Vector<AlumniMasterModel> v = amservice.getalumni();
                                            for (AlumniMasterModel amodel : v) {
                                            
      out.write("\r\n");
      out.write("                                            <option value=\"");
      out.print(amodel.getid());
      out.write('"');
      out.write('>');
      out.print(amodel.getid());
      out.write("</option>\r\n");
      out.write("                                            ");

                                            }
                                            
      out.write("\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group mt-3\">\r\n");
      out.write("                                        <label for=\"batchSelect\">Select Batch ID</label>\r\n");
      out.write("                                        <select class=\"form-control\" id=\"batchSelect\" name=\"bid\">\r\n");
      out.write("                                            <option value=\"\">Select ID</option>\r\n");
      out.write("                                            ");

                                            BatchMasterService bmservice = new BatchMasterServiceImpl();
                                            Vector<BatchMasterModel> v1 = bmservice.getbtchdetails();
                                            for (BatchMasterModel bm : v1) {
                                            
      out.write("\r\n");
      out.write("                                            <option value=\"");
      out.print(bm.getBid());
      out.write('"');
      out.write('>');
      out.print(bm.getBid());
      out.write("</option>\r\n");
      out.write("                                            ");

                                            }
                                            
      out.write("\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group mt-3\">\r\n");
      out.write("                                        <label for=\"txtAlumniName\">Alumni Name</label>\r\n");
      out.write("                                        <input type=\"text\" name=\"alumniName\" id=\"txtAlumniName\" class=\"form-control\" placeholder=\"Enter Alumni Name\" autocomplete=\"off\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"txtEmail\">Alumni Email</label>\r\n");
      out.write("                                        <input type=\"email\" name=\"email\" id=\"txtEmail\" class=\"form-control\" placeholder=\"Enter Alumni Email-Id\" autocomplete=\"off\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"txtContact\">Alumni Contact</label>\r\n");
      out.write("                                        <input type=\"text\" name=\"contact\" id=\"txtContact\" class=\"form-control\" placeholder=\"Enter Alumni Contact\" autocomplete=\"off\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"txtAge\">Alumni Age</label>\r\n");
      out.write("                                        <input type=\"number\" name=\"age\" id=\"txtAge\" class=\"form-control\" placeholder=\"Enter Alumni Age\" autocomplete=\"off\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"txtCompName\">Alumni Company Name</label>\r\n");
      out.write("                                        <input type=\"text\" name=\"compname\" id=\"txtCompName\" class=\"form-control\" placeholder=\"Enter Alumni Company Name\" autocomplete=\"off\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group d-flex justify-content-center\">\r\n");
      out.write("                                        <input type='submit' name='s' id=\"btn\" value='Update Alumni' class=\"btn btn-primary\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div> <!-- updateFields -->\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div> <!-- form-container -->\r\n");
      out.write("                    </div> <!-- tab-pane -->\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"v-pills-profile\" role=\"tabpanel\" aria-labelledby=\"v-pills-profile-tab\"></div>\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"v-pills-messages\" role=\"tabpanel\" aria-labelledby=\"v-pills-messages-tab\"></div>\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"v-pills-settings\" role=\"tabpanel\" aria-labelledby=\"v-pills-settings-tab\"></div>\r\n");
      out.write("                </div> <!-- tab-content -->\r\n");
      out.write("            </div> <!-- col-md-9 -->\r\n");
      out.write("        </div> <!-- row -->\r\n");
      out.write("    </div> <!-- container -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
